= Noise Protocol for Java

image:https://api.bintray.com/packages/emerald/noise-java/noise/images/download.svg["Bintray", link="https://bintray.com/emerald/noise-java/noise/"]
image:https://img.shields.io/github/license/emeraldpay/noise-java.svg?maxAge=2592000["License", link="https://github.com/emeraldpay/noise-java/blob/master/LICENSE"]

Java Library that offers the features in the base Noise spec. It doesn't implement Noise Pipes, NoiseLingoSocket or
other newer extensions.

== Original Work

This library is a fork of https://github.com/rweather/noise-java[Rhys Weatherley's Noise-Java library], and
https://github.com/corda/noise-java[Mike Hearn's fork], who modernized it to benefit from newer Java versions.

Differences from the https://github.com/rweather/noise-java[Rhys Weatherley's Noise-Java library] upstream project include:

* Uses Gradle for the build and JavaDocs.
* Fully modular when used on Java 9+ (has a module-info descriptor)
* Crypto fallbacks have been removed. This version can only use the JDK's native AES/GCM support. This is because
 for users on modern Java the native AES/GCM support is better: it's hardware accelerated using
 AES-NI, and removing emulations and fallback logic makes the library smaller and easier to
 review. The small size and easy auditability of Noise protocols is one of their primary benefits.
* Updated to more modern Java language constructs (still targets Java 8 runtimes), and fixed various
 static analysis warnings. Fleshed out a few JavaDocs.
* Added the test vectors from Noise-C and made them run by default as part of `gradle test`.

As a consequence of these changes, this version may be unsuitable for pre-Lollipop Android versions.
The original might be better if you need to support those cases.

The main difference from https://github.com/corda/noise-java[Mike Hearn's fork] is that current fork is accessible
through a public repository on Bintray.

== Usage

=== Dependency

.Gradle
----
repositories {
    jcenter()
    maven { url "https://dl.bintray.com/emerald/noise-java" }
}

dependencies {
    compile 'io.emeraldpay.noise:noise:1.0'
}
----

.Maven
----
<repositories>
  <repository>
    <id>bintray-emerald-noise-java</id>
    <name>bintray</name>
    <url>https://dl.bintray.com/emerald/noise-java</url>
    <snapshots><enabled>false</enabled></snapshots>
</repository>
</repositories>

<dependency>
	<groupId>io.emeraldpay.noise</groupId>
	<artifactId>noise</artifactId>
	<version>1.0</version>
	<type>pom</type>
</dependency>
----

== License

MIT License

Copyright (C) 2016 Southern Storm Software, Pty Ltd.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.